// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlkooaftxzbeyumdpjmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsa29vYWZ0eHpiZXl1bWRwam1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjIxODEsImV4cCI6MjA3MjczODE4MX0.EsRtzhrF6KoXultQr4eoYYrMnwa-ZBZ26aJ-7gE7k2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});